consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  CreateBottlePayload:
    description: BottlePayload is the type used to create bottles
    properties:
      name:
        description: Name of bottle
        minLength: 1
        type: string
      rating:
        description: Rating of bottle
        maximum: 5
        minimum: 1
        type: integer
      vintage:
        description: Vintage of bottle
        minimum: 1900
        type: integer
    required:
    - name
    - vintage
    - rating
    title: CreateBottlePayload
    type: object
  Error:
    description: Error response media type
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1.458609e+09
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1.458609e+09
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.api.error+json'
    type: object
  bottle:
    example:
      ID: 9.910734e+16
      name: Et saepe.
      rating: 4.9685924e+18
      vintage: 1.280148e+18
    properties:
      ID:
        description: Unique bottle ID
        example: 6.438311e+18
        format: int64
        type: integer
      name:
        description: Name of bottle
        example: p
        minLength: 1
        type: string
      rating:
        description: Rating of bottle
        example: 3
        maximum: 5
        minimum: 1
        type: integer
      vintage:
        description: Vintage of bottle
        example: 3410
        minimum: 1900
        type: integer
    required:
    - ID
    - name
    - vintage
    - rating
    title: 'Mediatype identifier: application/vnd.gophercon.goa.bottle'
    type: object
host: localhost:8080
info:
  description: The wine review service
  version: ""
paths:
  /bottles:
    post:
      description: creates a bottle
      operationId: bottle#create
      parameters:
      - description: BottlePayload is the type used to create bottles
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/CreateBottlePayload'
      responses:
        "201":
          description: Created
      summary: create bottle
      tags:
      - bottle
  /bottles/{id}:
    get:
      description: shows a bottle
      operationId: bottle#show
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bottle'
      summary: show bottle
      tags:
      - bottle
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/Error'
      summary: Download swagger-ui/
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      summary: Download swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  Created:
    description: Created
swagger: "2.0"
